tasks:
  - source: code_A.ipynb
    params:
      input_csv: input_data/sample_utf8.csv
    product:
      nb: output/log_code_A.ipynb
      data: output/output_A.csv

  - source: code_B.ipynb
    product:
      nb: output/log_code_B.ipynb
      data: output/output_B.csv

  - source: code_C.ipynb
    product:
      nb: output/log_code_C.ipynb
      data: output/output_C.csv
